services:
  discordjs:
    build:
      context: https://github.com/k4mien/lavalink_djs.git
      dockerfile: Dockerfile
      target: prod
    restart: always
    networks:
      - lavalink
    container_name: dc-docker

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: always
    environment:
      - _JAVA_OPTIONS=-Xmx4G
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    networks:
      - lavalink
    expose:
      - 2333
    ports:
      - "2333:2333"

networks:
  lavalink:
    name: lavalink