services:
  discordjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: always
    networks:
      - lavalink
    container_name: dc-docker

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: always
    environment:
      - _JAVA_OPTIONS=-Xmx1G
    env_file:
      - application.env
    networks:
      - lavalink
    expose:
      - 2333
    ports:
      - "2333:2333"

networks:
  lavalink:
    name: lavalink