services:
  discordjs:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./src/package.json
        - action: rebuild
          path: ./src/package-lock.json
    networks:
      - lavalink
    container_name: dc-docker

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx4G
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml # mount application.yml from the same directory or use environment variables
    #      - ./plugins/:/opt/Lavalink/plugins/ # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
    networks:
      - lavalink
    expose:
      - 2333 # lavalink exposes port to connect to for other containers (this is for documentation purposes only)
    ports:
      - "2333:2333" # you only need this if you want to make your lavalink accessible from outside of containers

networks:
  lavalink: # create a lavalink network you can add other containers to, to give them access to Lavalink
    name: lavalink