services:
  discordjs:
    build:
      dockerfile: Dockerfile
      context: .
      target: prod
    networks:
      - lavalink

  lavalink:
    container_name: lavalink
    image: ghcr.io/lavalink-devs/lavalink:4
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx4G
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    networks:
      - lavalink
    expose:
      - 2333
    ports:
      - "2333:2333"

networks:
  lavalink:
    name: lavalink