version: "3.9"

services:
  discordjs:
    build:
      context: .
      args:
        - NODE_ENV=development
      dockerfile: Dockerfile
    volumes:
      - ./src:/node/app
      - ./src/package.json:/node/package.json
      - ./src/package-lock.json:/node/package-lock.json
      - ndm:/node/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - lavalink
    container_name: dc-docker
    command: npm run dev

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx4G
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml # mount application.yml from the same directory or use environment variables
    #      - ./plugins/:/opt/Lavalink/plugins/ # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
    networks:
      - lavalink
    expose:
      - 2333 # lavalink exposes port to connect to for other containers (this is for documentation purposes only)
    ports:
      - "2333:2333" # you only need this if you want to make your lavalink accessible from outside of containers

networks:
  lavalink: # create a lavalink network you can add other containers to, to give them access to Lavalink
    name: lavalink

volumes:
  ndm: