---
name: Linter

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    name: Linting
    permissions:
      contents: read
      statuses: write
    # FIXME: customize uri to point to your own reusable linter repository
    uses: k4mien/super-linter-bf/.github/workflows/reusable-super-linter.yaml@main
    with:
      filter-regex-include: src/.*